# Documentation can be found here: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/vhost/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/null93/vhost/internal.Version={{ .Version }}"
checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/null93/vhost
    description: NGINX config structure for provisioning virtual hosts with a CLI tool
    maintainer: Rafael Grigorian <rafael@grigorian.org>
    vendor: null93
    bindir: /usr/bin
    contents:
    - src: examples
      dst: /var/lib/vhost/templates
    - type: dir
      dst: /var/lib/vhost/checkpoints
    - type: dir
      dst: /etc/vhost
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - repository:
      owner: null93
      name: homebrew-tap
    directory: Formula
    goarm: "7"
    homepage: https://github.com/null93/vhost
    description: NGINX config structure for provisioning virtual hosts with a CLI tool
    test: |
      system "#{bin}/vhost -v"
